map.createPane('indexPanepn_atm');
map.getPane('indexPanepn_atm').style.zIndex = 600;
map.createPane('indexPanepn_bank');
map.getPane('indexPanepn_bank').style.zIndex = 600;
map.createPane('indexPanepn_beauty');
map.getPane('indexPanepn_beauty').style.zIndex = 600;
map.createPane('indexPanepn_cafe');
map.getPane('indexPanepn_cafe').style.zIndex = 600;
map.createPane('indexPanepn_clock');
map.getPane('indexPanepn_clock').style.zIndex = 600;
map.createPane('indexPanepn_clothes');
map.getPane('indexPanepn_clothes').style.zIndex = 600;
map.createPane('indexPanepn_doctors');
map.getPane('indexPanepn_doctors').style.zIndex = 600;
map.createPane('indexPanepn_electronics');
map.getPane('indexPanepn_electronics').style.zIndex = 600;
map.createPane('indexPanepn_emergency');
map.getPane('indexPanepn_emergency').style.zIndex = 600;
map.createPane('indexPanepn_fap');
map.getPane('indexPanepn_fap').style.zIndex = 600;
map.createPane('indexPanepn_fitness');
map.getPane('indexPanepn_fitness').style.zIndex = 600;
map.createPane('indexPanepn_grocery');
map.getPane('indexPanepn_grocery').style.zIndex = 600;
map.createPane('indexPanepn_haircut');
map.getPane('indexPanepn_haircut').style.zIndex = 600;
map.createPane('indexPanepn_homeshop');
map.getPane('indexPanepn_homeshop').style.zIndex = 600;
map.createPane('indexPanepn_kids');
map.getPane('indexPanepn_kids').style.zIndex = 600;
map.createPane('indexPanepn_kpndergarten');
map.getPane('indexPanepn_kpndergarten').style.zIndex = 600;
map.createPane('indexPanepn_library');
map.getPane('indexPanepn_library').style.zIndex = 600;
map.createPane('indexPanepn_lotery');
map.getPane('indexPanepn_lotery').style.zIndex = 600;
map.createPane('indexPanepn_monument');
map.getPane('indexPanepn_monument').style.zIndex = 600;
map.createPane('indexPanepn_pharmacy');
map.getPane('indexPanepn_pharmacy').style.zIndex = 600;
map.createPane('indexPanepn_picnic');
map.getPane('indexPanepn_picnic').style.zIndex = 600;
map.createPane('indexPanepn_pnsurance');
map.getPane('indexPanepn_pnsurance').style.zIndex = 600;
map.createPane('indexPanepn_repair');
map.getPane('indexPanepn_repair').style.zIndex = 600;
map.createPane('indexPanepn_schoolsport');
map.getPane('indexPanepn_schoolsport').style.zIndex = 600;
map.createPane('indexPanepn_serv_org_sector');
map.getPane('indexPanepn_serv_org_sector').style.zIndex = 600;
map.createPane('indexPanepn_serv_org');
map.getPane('indexPanepn_serv_org').style.zIndex = 600;
map.createPane('indexPanepn_shop_build');
map.getPane('indexPanepn_shop_build').style.zIndex = 600;
map.createPane('indexPanepn_shop');
map.getPane('indexPanepn_shop').style.zIndex = 600;
map.createPane('indexPanepn_special');
map.getPane('indexPanepn_special').style.zIndex = 600;
map.createPane('indexPanepn_sport_general');
map.getPane('indexPanepn_sport_general').style.zIndex = 600;